//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class usuario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public usuario()
        {
            this.compra = new HashSet<compra>();
        }
    
        public int id { get; set; }

        [Required(ErrorMessage ="No puede ir vacio")]
        [StringLength(15,ErrorMessage ="Exedio el limite de caracteres")]
        public string nombre { get; set; }

        [Required(ErrorMessage = "No puede ir vacio")]
        public string apellido { get; set; }

        
        public Nullable<System.DateTime> fecha_nacimiento { get; set; }

        [Required(ErrorMessage = "No puede ir vacio")]
        [EmailAddress(ErrorMessage ="No tiene formato email")]
        public string email { get; set; }

        [Required(ErrorMessage = "No puede ir vacio")]
        public string password { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<compra> compra { get; set; }
    }
}
